# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adj_mat <- function(grand_nbd) {
    .Call(`_NNDM_adj_mat`, grand_nbd)
}

Tmats <- function(n, p, L, k, all_nbd, x, adj_mat, phi0seq, grand_means, grand_vars, mu0, nu0, gamma0) {
    .Call(`_NNDM_Tmats`, n, p, L, k, all_nbd, x, adj_mat, phi0seq, grand_means, grand_vars, mu0, nu0, gamma0)
}

adj_mat_univ <- function(grand_nbd) {
    .Call(`_NNDM_adj_mat_univ`, grand_nbd)
}

Tmats_univ <- function(n, L, k, all_nbd, x, adj_mat, phi0seq, grand_means, grand_vars, mu0, nu0, gamma0) {
    .Call(`_NNDM_Tmats_univ`, n, L, k, all_nbd, x, adj_mat, phi0seq, grand_means, grand_vars, mu0, nu0, gamma0)
}

random_gamma <- function(a) {
    .Call(`_NNDM_random_gamma`, a)
}

random_gaussian <- function(p) {
    .Call(`_NNDM_random_gaussian`, p)
}

set_seed <- function(seed) {
    invisible(.Call(`_NNDM_set_seed`, seed))
}

fdraws <- function(n, p, s, MC, wtvec, mu_vec, psi_inv, gamman, nun, inputpt) {
    .Call(`_NNDM_fdraws`, n, p, s, MC, wtvec, mu_vec, psi_inv, gamman, nun, inputpt)
}

random_gamma_univ <- function(a) {
    .Call(`_NNDM_random_gamma_univ`, a)
}

fdraws_univ <- function(n, s, MC, wtvec, mu_vec, rate_par, gamman, nun, inputpt) {
    .Call(`_NNDM_fdraws_univ`, n, s, MC, wtvec, mu_vec, rate_par, gamman, nun, inputpt)
}

